### ISSUE TITLE
Need linebreaks filter

### ISSUE THREAD

**Issue by catlips** [tbtimes/ledeTwo#1]
Lede had a _nunjucks_ filter that inserted a `<p>` tag everywhere there was a newline in text contained within the bits/text.html template. Need this here.

**Comment by catlips** [comment]
Sass `@import` links are not relative, they're from the project root. Thus, in project test, I have to use paths like `@import "test/bootstrap";` and `"@import "test/bootstrap/responsive-utilities";`.

**Comment by ejmurra** [comment]
Fixed in a0344c1df171d20e9cc00bc42bfaf0665b9225fc
