### ISSUE TITLE
Need fallbacks filter

### ISSUE THREAD

**Issue by catlips** [tbtimes/ledeTwo#11]
Used to supply fallback value when none is specified

**Comment by aplayford** [comment]
FYI I think there might be a built-in version of this in Nunjucks. (I
didn't know it existed when I wrote fallback; found it later). Check out
`default` (or `d`). http://jinja.pocoo.org/docs/dev/templates/#default

**Comment by catlips** [comment]
There's a built-in 'defaults' filter that does the same thing, it turns out.
