### ISSUE TITLE
Ensure AML parser isn't omitting bracketed text

### ISSUE THREAD

**Issue by aplayford** [tbtimes/ledeTwo#3]
@abstrctn implemented this for us in the main @newsdev/archieml.org branch for us (making it possible to disable comments). Let's take advantage of this flag: https://github.com/newsdev/archieml.org/issues/14

**Comment by aplayford** [comment]
This _might_ have been depreciated already, actually. Let's check...

**Comment by ejmurra** [comment]
Yeah, aml does this by default now.
